### ISSUE TITLE
Building master branch fails due to new tokio-util version

### ISSUE THREAD

**Issue by pfrenssen** [actix/examples#318]
Current master branch fails because we are linking both against `tokio-util` versions 0.2.0 and 0.3.1.

This is probably caused by https://github.com/benashford/redis-async-rs/pull/52

**Comment by JohnTitor** [comment]
Should be fixed in `actix-redis` 0.8.2.

**Comment by pfrenssen** [comment]
It is still failing with `actix-redis` 0.8.2. It seems that also `tokio-postgres` 0.5.3 and above is pulling in the new `tokio-util`.

**Comment by pfrenssen** [comment]
Never mind, I see that the latest build is green again, it was probably an artifact in my local Cargo.lock.

If anyone else would struggle with this, here is the patch that solved it for me locally:

```
diff --git a/async_pg/Cargo.toml b/async_pg/Cargo.toml
index 9ea1767..3ba3363 100644
--- a/async_pg/Cargo.toml
+++ b/async_pg/Cargo.toml
@@ -15,4 +15,4 @@ dotenv = "0.15.0"
 serde = { version = "1.0.104", features = ["derive"] }
 tokio-pg-mapper = "0.1"
 tokio-pg-mapper-derive = "0.1"
-tokio-postgres = "0.5.1"
+tokio-postgres = ">=0.5.1, <0.5.3"
diff --git a/redis/Cargo.toml b/redis/Cargo.toml
index db64a47..752018c 100644
--- a/redis/Cargo.toml
+++ b/redis/Cargo.toml
@@ -8,8 +8,8 @@ edition = "2018"
 actix = "0.9.0"
 actix-rt = "1.0.0"
 actix-web = "2.0.0"
-actix-redis = "0.8.0"
+actix-redis = "0.8.2"
 futures = "0.3.1"
-redis-async = "0.6.1"
+redis-async = ">=0.6.0, <0.6.3"
 serde = { version = "1.0.71", features = ["derive"] }
 env_logger = "0.7"
```
